language: cpp
compiler:
  - clang
  - gcc
env:
  - TARGET=coverage
  - TARGET=debug
  # - TARGET=debug.nounity
  # We can specify any combination of builds here, for example, to
  # include release builds, too, uncomment the following lines.
  #- TARGET=release
  #- TARGET=release.nounity
matrix:
  exclude:
    - env: TARGET=coverage
      compiler: clang
before_install:
  - bin/ci/ubuntu/install-dependencies.sh
script:
  - bin/ci/ubuntu/build-and-test.sh
notifications:
  email:
    false
  irc:
    channels:
      - "chat.freenode.net#ripple-dev"
